### ISSUE TITLE
Non-English translations of tag names give no search results

### ISSUE THREAD

**Issue by dgramsey** [wwoast/redpanda-lineage#205]
When I set my language to English and click on a tag name from the list in the "About" page, I get results with that tag. However, when I set my language to Japanese or Chinese and click on a tag name, nothing happens. The problem appears to be that the query is using the non-English translation directly, but tags can only be found with their English name. For example, if I set my language to Japanese and click on "舌ヒラヒラ", the URL changes to "https://redpandafinder.com/#query/舌ヒラヒラ", and nothing happens. But if i manually change the URL to "https://redpandafinder.com/#query/air tasting", I get results in Japanese for the tag, as expected.

**Comment by wwoast** [comment]
Good find! This looks like some kind of error in the processing for these other-language tags, cause I know this used to work correctly. I'll look at this. Thanks for reporting!

**Comment by wwoast** [comment]
The heading tag was broken (not displaying the right tag) too. Fixed: https://github.com/wwoast/redpanda-lineage/commit/5ee0a92446f238bf2d4ecbfd2aa8084c4653ab3e
