### ISSUE TITLE
New copy of tag list added every time you return to the "About" page

### ISSUE THREAD

**Issue by dgramsey** [wwoast/redpanda-lineage#206]
Every time you go to the "About" page from a different page on the site, a new copy of the tag list is added to the bottom. For example, if I go the "About" page, click on a tag, then go back to the "About" page, there will be two copies of the tag list. If I then click on another tag and go back to the "About" page, there will be three copies.

**Comment by wwoast** [comment]
Eek, why is it doing that :-1: I'll try and fix this shortly!

**Comment by wwoast** [comment]
I had to add logic to prevent it adding the tag list if my placeholder spot already had valid HTML childNodes.
