### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by akapanredpanda** [wwoast/redpanda-lineage#256]
I'd like to help translating Red Panda Finder to Portuguese. I'm Brazilian, so I can do this job.

**Comment by wwoast** [comment]
I'd love the help :) Almost everything translation wise is in `language.js` with a little bit of data model things in `pandas.js` and some things related to search keywords and tags in `parse.js`.

I have a recent PR for [translating it to Spanish](https://github.com/wwoast/redpanda-lineage/pull/254) but there was a lot of incremental commits prior to this PR so it doesn't encompass all the possible things to change.

**Comment by wwoast** [comment]
https://github.com/wwoast/redpanda-lineage/pull/257 :heart:
