### ISSUE TITLE
Unknown location id breaks zoo and panda page views

### ISSUE THREAD

**Issue by SimonLarsen** [wwoast/redpanda-lineage#274]
Panda `1408` introduced in #273 breaks the site when viewing [https://redpandafinder.com/#profile/1408](https://redpandafinder.com/#profile/1408) and [https://redpandafinder.com/#zoo/-312](https://redpandafinder.com/#zoo/-312). The errors occur because the `location.3` field has an unknown zoo id, resulting in errors in `Show.acquireLocationList` and `Show.results.pandaDetails` in `show.js`.

We can fix this by either:
1. changing `1408_maya.txt` or
2. adding the necessary checks in `show.js` to handle this gracefully.

I'd be happy to submit a PR with a fix, but I am unsure if this is considered a bug in the frontend, or if unknown locations should be handled differently.

**Comment by wwoast** [comment]
The schema ideally shouldn't fail due to missing locations. I think ideally I'd like "unknown" to be handled as a special value, where the existing code probably just expects numbers. You're very kind to help improve this Simon -- thank you!
