### ISSUE TITLE
Hinata and Miho are not in Himeji Central Park.

### ISSUE THREAD

**Issue by hachi-firefoxpanda** [wwoast/redpanda-lineage#64]
https://github.com/wwoast/redpanda-lineage/blob/fac52086caee53fab195ff6f19dfefb584e3d522/pandas/0014_himeji/0032_hinata.txt#L34

Hinata and Miho(0033) are in Himeji "Municipal" Zoo.
(There are two zoos in Himeji-city.)

Himeji Municipal Zoo
 68 Honmachi, Himeji-shi, Hyogo pref.  ZIP:670-0012

<<Info in Japanese>>
姫路市立動物園
〒670-0012 兵庫県姫路市本町68

**Comment by wwoast** [comment]
https://github.com/wwoast/redpanda-lineage/commit/94cb15fbb4e20d3b73bd360a39122bef1c3399ba
https://github.com/wwoast/redpanda-lineage/commit/edce0e7bbd9630509d0b3fccf333a6b4353643d3
https://github.com/wwoast/redpanda-lineage/commit/bdc01eb1b17003f36eadf7ad4f895b8f20b1feab

Thanks for the correction Hachi ;)
