### ISSUE TITLE
Raichi's father is Tenten!

### ISSUE THREAD

**Issue by hachi-firefoxpanda** [wwoast/redpanda-lineage#66]
https://github.com/wwoast/redpanda-lineage/blob/5ab1e004a66547a22539b52f091f379adb85f428/pandas/0001_ichikawa/0004_lychee.txt#L4

Father of Raichi, Rinta, Sora, Kai and Aqua is Tenten(天天/テンテン).

**Comment by wwoast** [comment]
https://github.com/wwoast/redpanda-lineage/commit/5c46a839d073bdd2c13ffdc5086a1f55bf766669

I'd been meaning to add this for a while :+1: Thank you Hachi-san! :wink: 

The only Tenten photos I have are in my Ichikawa panda family tree books. If you have any favorites I can link to in the dataset, from Instagram or elsewhere, let me know :smile:

**Comment by hachi-firefoxpanda** [comment]
I've sent you info of Tenten at IG!

2018年8月24日金曜日、Justin Fairchild<notifications@github.com>さんは書きました:

**Comment by wwoast** [comment]
https://github.com/wwoast/redpanda-lineage/commit/b35dfaa6376965a40f8c8f9521cb3715aba88c3d

We have Ten-Ten photos and info now :)

**Comment by hachi-firefoxpanda** [comment]
Thank you for your efforts!
